# Last Updated: 2018-12-27
# Teddy Whitelist

pihole -w alluremedia.com.au
pihole -w android.clients.google.com
pihole -w aolcdn.com
pihole -w api.facebook.com
pihole -w api.io.mi.com
pihole -w api.ipify.org
pihole -w apm.wetest.qq.com
pihole -w appleid.apple.com
pihole -w apps.skype.com
pihole -w apresolve.spotify.com
pihole -w as.y.atwola.com
pihole -w auth.api.gitv.tv
pihole -w avgle.com
pihole -w bit.ly
pihole -w c.s-microsoft.com
pihole -w cdn.fbsbx.com
pihole -w cdn.optimizely.com
pihole -w clients1.google.com
pihole -w clients2.google.com
pihole -w clients3.google.com
pihole -w clients4.google.com
pihole -w clients5.google.com
pihole -w clients6.google.com
pihole -w connect.facebook.com
pihole -w connect.facebook.net
pihole -w cs.mbgame.gamesafe.qq.com
pihole -w dl.dropbox.com
pihole -w dl.google.com
pihole -w ea.com
pihole -w edge-mqtt.facebook.com
pihole -w err.taobao.com
pihole -w g.alicdn.com
pihole -w g.live.com
pihole -w github.com
pihole -w goo.gl
pihole -w graph.facebook.com
pihole -w gs-loc-new.ls-apple.com.akadns.net
pihole -w i.s-microsoft.com
pihole -w id.google.com.hk
pihole -w idc.receiver.tdm.qq.com
pihole -w idcconfig.gcloud.qq.com
pihole -w ios.bugly.qq.com
pihole -w ir0.mobify.com
pihole -w itunes.apple.com
pihole -w jingyan.baidu.com
pihole -w keystone.mwbsys.com
pihole -w login.live.com
pihole -w m.hotmail.com
pihole -w metrics.icloud.com
pihole -w mobile.pipe.aria.microsoft.com
pihole -w msftncsi.com
pihole -w netflix.com
pihole -w o.aolcdn.com
pihole -w ocsp.apple.com
pihole -w officeclient.microsoft.com
pihole -w outlook.office365.com
pihole -w p10-buy.itunes-apple.com.akadns.net
pihole -w p37-imap.mail.me.com.akadns.net
pihole -w pingma.qq.com
pihole -w placehold.it
pihole -w placeholdit.imgix.net
pihole -w pricelist.skype.com
pihole -w prod-kr.contentsync-onenote.com.akadns.net
pihole -w products.office.com
pihole -w profile.gc-apple.com.akadns.net
pihole -w s.gateway.messenger.live.com
pihole -w s.shopify.com
pihole -w s.update.fbsbx.com
pihole -w s.youtube.com
pihole -w s1.symcb.com
pihole -w s2.symcb.com
pihole -w s3.amazonaws.com
pihole -w s3.symcb.com
pihole -w s4.symcb.com
pihole -w s5.symcb.com
pihole -w sa.symcb.com
pihole -w scontent.xx.fbcdn.net
pihole -w spclient.wg.spotify.com
pihole -w star-mini.c10r.facebook.com
pihole -w star.c10r.facebook.com
pihole -w tinyurl.com
pihole -w tomshardware.com
pihole -w trade.tmall.com
pihole -w ui.skype.com
pihole -w union.video.qq.com
pihole -w video-stats.l.google.com
pihole -w whatismyipaddress.com
pihole -w woocall.sina.com.cn
pihole -w wp.me
pihole -w www-cdn.icloud.com.akadns.net
pihole -w www.bit.ly
pihole -w www.msftncsi.com
pihole -w ynuf.alipay.com